### PR TITLE
feat(discord): link to level in times

### PR DESCRIPTION
**Pull request by j-masci**
would def request a review on this as I don't know how to test it or if it even works as intended.

apparently, you can write custom links using format described here: https://support.discord.com/hc/en-us/community/posts/360061776032-How-to-make-clickable-text-hyperlink-

but only works using discord chat bot.

Also, the functions were hard to test because they both build the message and sent it at the same time. So the best I could do was take the json examples from /events and feed them into the functions and console log their output, which is below.

image

### CODE REVIEW

**Comment by j-masci** [comment]
probably the worst that happens is you see exactly that output in discord times. but hopefully you see a link with text as the level name.

**Comment by sunehs** [comment]
you _can_ set up own bot and server as mentioned in config if you really want to test, otherwise I'll try it sometime on the test bot

instead of hardcoded url you can use config.discord.url

**Comment by j-masci** [comment]
Well I'm quite confident nothing will break. Just different messages will get sent to discord. I'm only 75% sure they will be formatted as intended. Testing won't hurt but either way I suppose.

**Comment by sunehs** [comment]
Link like this only works in embeds, which looks like this. Each line will be 3 times as high.

discordembed

**Comment by j-masci** [comment]
I see well thx for testing. I'll take another look soon.

**Comment by j-masci** [comment]
i'll close this for now and maybe look later.

**Pull request closed without merging**
